apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaniko-data-pvc
  namespace: test
spec:
  storageClassName: hostpath
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteMany
  volumeName: kaniko-data-pv
