apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-sa-rolebinding
  namespace: test
subjects:
  - kind: ServiceAccount
    name: test-sa
    namespace: test
roleRef:
  kind: Role
  name: test-sa-role
  apiGroup: rbac.authorization.k8s.io
