# HOST_PATH is the path to the directory on the host where the Kaniko data will be stored.
# REGISTRY_IP_ADDRESS is the IP address of the registry.

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
nodes:
- role: control-plane
  extraMounts:
    # NB! Change the hostPath to a directory on your host
    - hostPath: HOST_PATH
      containerPath: /kaniko-data
containerdConfigPatches:

  # Change the IP address to the IP address of your registry
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."REGISTRY_IP_ADDRESS:5000"]
    endpoint = ["http://REGISTRY_IP_ADDRESS:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."REGISTRY_IP_ADDRESS:5000".tls]
    insecure_skip_verify = true