apiVersion: apps/v1
kind: Deployment
metadata:
  name: easycontainers-spring-boot-test-app-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easycontainers-spring-boot-test-app
  template:
    metadata:
      labels:
        app: easycontainers-spring-boot-test-app
    spec:
      serviceAccountName: test-sa
      containers:
        - name:  easycontainers-spring-boot-test-app-container
          image: localhost:5000/easycontainers-spring-boot-test-app:latest
          ports:
            - containerPort: 8080
            - containerPort: 9999
            - containerPort: 5005
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9999
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9999
            initialDelaySeconds: 20
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: easycontainers-spring-boot-test-app-service
  namespace: test
spec:
  selector:
    app: easycontainers-spring-boot-test-app
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: actuator-port
      protocol: TCP
      port: 9999
      targetPort: 9999
      nodePort: 30099
  type: NodePort

