image-registry:
  url: http://192.168.1.86:5000

### Logging ###
logging:
  stdout-appender-threshold-level: TRACE
  trace-appender-threshold-level: TRACE
  level:
    root: INFO
    no.acntech: TRACE
    org.springframework: INFO
